version: '3.8'
services:
balluff-bcm-sensor-aas:
    image: registry.gitlab.com/novaiiot/modul4r/ssf/balluff-bcm-sensor-aas:324c029a68357c604f40aa3c5549a5775789dd61
    container_name: balluff-bcm-sensor-aas
    restart: unless-stopped
    network_mode: "bridge"
    ports:
      - target: 1880
        published: "1815"
        protocol: tcp
    environment:
      - PORT_FORWARDING=1874
      - HOST=localhost
      - BROKER_SERVICE_HOST=localhost
      - BROKER_SERVICE_PORT=1883
    deploy:
      resources:
        limits:
          cpus: "0.1"
        reservations:
          cpus: "0.05"

x-casaos:
  main: balluff-bcm-sensor-aas
  architectures:
    - amd64
  author: Uninova
  category: AAS
  developer: Uninova
  icon: https://raw.githubusercontent.com/mreis1986/CasaOS-AppStore/balluff-bcm-sensor-aass/icon.png
  thumbnail: https://raw.githubusercontent.com/mreis1986/CasaOS-AppStore/balluff-bcm-sensor-aass/icon.png
  screenshot_link:
    - https://raw.githubusercontent.com/mreis1986/CasaOS-AppStore/balluff-bcm-sensor-aass/screenshot-1.png
    - https://raw.githubusercontent.com/mreis1986/CasaOS-AppStore/balluff-bcm-sensor-aass/screenshot-2.png
    - https://raw.githubusercontent.com/mreis1986/CasaOS-AppStore/balluff-bcm-sensor-aass/screenshot-3.png
  scheme: http
  hostname: ""
  index: /
  description:
    en_us: Implementation of the Asset Administration Shell by NOVA School of Science and Technology

  tagline:
    en_us: Implementation of the Asset Administration Shell by NOVA School of Science and Technology

  tips:
    en_us: User "admin" as username and "password" as password

  title:
    en_us: novaas
  port_map: "1815"