version: '3.8'
services:
beckhoff-xplanar-aas:
    image: registry.gitlab.com/novaiiot/modul4r/ssf/beckhoff-xplanar-aas:bce4cf2391d10bc005ddeb9e190e98b2e7ed5094
    container_name: beckhoff-xplanar-aas
    restart: unless-stopped
    network_mode: "bridge"
    ports:
      - target: 1880
        published: "1814"
        protocol: tcp
    environment:
      - PORT_FORWARDING=1875
      - HOST=localhost
      - BROKER_SERVICE_HOST=localhost
      - BROKER_SERVICE_PORT=1883
    deploy:
      resources:
        limits:
          cpus: "0.1"
        reservations:
          cpus: "0.05"

x-casaos:
  main: beckhoff-xplanar-aas
  architectures:
    - amd64
  author: Uninova
  category: AAS
  developer: Uninova
  icon: https://raw.githubusercontent.com/mreis1986/CasaOS-AppStore/beckhoff-xplanar-aass/icon.png
  thumbnail: https://raw.githubusercontent.com/mreis1986/CasaOS-AppStore/beckhoff-xplanar-aass/icon.png
  screenshot_link:
    - https://raw.githubusercontent.com/mreis1986/CasaOS-AppStore/beckhoff-xplanar-aass/screenshot-1.png
    - https://raw.githubusercontent.com/mreis1986/CasaOS-AppStore/beckhoff-xplanar-aass/screenshot-2.png
    - https://raw.githubusercontent.com/mreis1986/CasaOS-AppStore/beckhoff-xplanar-aass/screenshot-3.png
  scheme: http
  hostname: ""
  index: /
  description:
    en_us: Implementation of the Asset Administration Shell by NOVA School of Science and Technology

  tagline:
    en_us: Implementation of the Asset Administration Shell by NOVA School of Science and Technology

  tips:
    en_us: User "admin" as username and "password" as password

  title:
    en_us: novaas
  port_map: "1814"