version: '3.8'

services:
  novaas:
    container_name: novaas
    image: "registry.gitlab.com/novaas/catalog/nova-school-of-science-and-technology/novaas:v1.0.0"
    restart: unless-stopped
    environment:
      - PORT_FORWARDING=${PORT_FORWARDING:-1880} 
      - HOST=${HOST:-localhost}
      - BROKER_SERVICE_HOST=${BROKER_SERVICE_HOST:-broker.local}
      - BROKER_SERVICE_PORT=${BROKER_SERVICE_PORT:-1883}
      - REPO_LOCATION=${REPO_LOCATION:-/data}
    ports:
      - "${PORT_FORWARDING:-1880}:1880"
    networks:
      - novaas_network

    x-casaos:
      main: novaas
      author: CasaOS Community
      category: Developer
      description:
        en_us: "Novaas is an advanced application for developers."
      developer: "Nova School of Science and Technology"
      icon: "https://cdn.jsdelivr.net/gh/mreis1986/CasaOS-AppStore@main/Apps/novaas/icon.png"
      tagline:
        en_us: "Cloud-native development environment."
      title:
        en_us: "Novaas"
      index: "/"
      port_map: "1880"

networks:
  novaas_network:
    driver: bridge
