version: '3.8'

services:
  novaas:
    image: registry.gitlab.com/novaas/catalog/nova-school-of-science-and-technology/novaas:2ad875f652514e8b9c1afbb793252f06a842b090
    container_name: novaas
    restart: unless-stopped
    network_mode: "host"
    environment:
      - PORT_FORWARD=1880
      - HOST=192.168.3.95
      - BROKER_SERVICE_HOST=192.168.3.95
      - BROKER_SERVICE_PORT=1880
      - REPO_LOCATION=/DATA/AppData/$AppID/data
    volumes:
      - /DATA/AppData/novaas/config:/config
    deploy:
      resources:
        limits:
          cpus: "0.1" # Low CPU Shares
        reservations:
          cpus: "0.05"

x-casaos:
  main: novaas
  architectures:
    - amd64
  author: LisonEvf
  category: AI
  developer: LisonEvf
  icon: https://raw.githubusercontent.com/mreis1986/CasaOS-AppStore/695ce2a6333dcd910cc45e889fcdb13fac1399ee/Apps/novaas/icon.png
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Anaconda3/thumbnail.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Anaconda3/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Anaconda3/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Anaconda3/screenshot-3.png
  scheme: http
  hostname: ""
  index: /
  description:
    en_us: Implementation of the Asset Administration Shell by NOVA School of Science and Technology

  tagline:
    en_us: Implementation of the Asset Administration Shell by NOVA School of Science and Technology

  tips:
    en_us: User "admin" as username and "password" as password

  title:
    en_us: novaas
  port_map: "1880"