version: '3'

services:
  novaas:
    image: "registry.gitlab.com/novaas/catalog/nova-school-of-science-and-technology/novaas:2ad875f652514e8b9c1afbb793252f06a842b090"
    deploy:
      resources:
        reservations:
          memory: 64M    
    restart: unless-stopped
    environment:
      PORT_FORWARDING: "1880"
      HOST: "192.168.3.95"
      BROKER_SERVICE_HOST: "192.168.3.95"
      BROKER_SERVICE_PORT: "1880"
      REPO_LOCATION: "/DATA/AppData/$AppID/data"
    volumes:
      - type: bind
        source: /DATA/AppData/novaas/config
        target: /config
    container_name: novaas
    network_mode: "host"  # Ensure you need this, or remove it to allow port mapping

x-casaos:
  architectures:
    - amd64
    - arm64
    - s390x
    - arm
  main: novaas
  author: CasaOS Team
  category: Developer
  description:
    en_us: Asset Administration Shell to manage things
  developer: Node-RED
  icon: https://raw.githubusercontent.com/mreis1986/CasaOS-AppStore/695ce2a6333dcd910cc45e889fcdb13fac1399ee/Apps/novaas/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Anaconda3/screenshot-1.png
  tagline:
    en_us: Asset Administration Shell for industrial automation
  thumbnail: https://raw.githubusercontent.com/mreis1986/CasaOS-AppStore/695ce2a6333dcd910cc45e889fcdb13fac1399ee/Apps/novaas/icon.png
  title:
    en_us: novaas
  index: /
  port_map: "1880"
