name: novaas
services:
  novaas:
    container_name: novaas
    image: "registry.gitlab.com/novaas/catalog/nova-school-of-science-and-technology/novaas:v1.0.0"
    restart: unless-stopped
    environment:
      - PORT_FORWARDING=${PORT_FORWARDING:-1880} 
      - HOST=${HOST:-localhost}
      - BROKER_SERVICE_HOST=${BROKER_SERVICE_HOST:-broker.local}
      - BROKER_SERVICE_PORT=${BROKER_SERVICE_PORT:-1883}
      - REPO_LOCATION=${REPO_LOCATION:-/data}
    ports:
      - "${PORT_FORWARDING:-1880}:1880"
    networks:
      - novaas_network

    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: ""
        - container: PGID
          description:
            en_us: ""
        - container: TZ
          description:
            en_us: ""
        - container: NOVAAS_USER
          description:
            en_us: ""
        - container: NOVAAS_PASS
          description:
            en_us: ""
      ports:
        - container: "1880"
          description:
            en_us: ""

      volumes:
        - container: /config
          description:
            en_us: ""
        - container: /downloads
          description:
            en_us: ""
    container_name: novaas
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: novaas
  author: CasaOS Team
  category: Downloader 
  description:
    en_us: Asset Administration Shell do things

  developer: Uninova
  icon: https://raw.githubusercontent.com/mreis1986/CasaOS-AppStore/695ce2a6333dcd910cc45e889fcdb13fac1399ee/Apps/novaas/icon.png
  screenshot_link:
    - https://raw.githubusercontent.com/mreis1986/CasaOS-AppStore/695ce2a6333dcd910cc45e889fcdb13fac1399ee/Apps/novaas/icon.png

  tagline:
    en_us: Asset Administration Shell 
  thumbnail: https://raw.githubusercontent.com/mreis1986/CasaOS-AppStore/695ce2a6333dcd910cc45e889fcdb13fac1399ee/Apps/novaas/icon.png
  tips:
    before_install:
      en_us: |
        Default Account

        | Username | Password |
        | -------- | -------- |
        | admin   | password |
  title:
    en_us: novaas
  port_map: "1880"
