version: '3'

services:
  novaas:
    args:
      - AAS_VERSION=${AAS_VERSION}
    image: "registry.gitlab.com/novaas/catalog/nova-school-of-science-and-technology/novaas"
    deploy:
      resources:
        reservations:
          memory: 64M    
    network_mode: "host"
    environment:
      - PORT_FORWARDING=1880
      - HOST=192.168.3.95
      - BROKER_SERVICE_HOST=192.168.3.95
      - BROKER_SERVICE_PORT=1880
      - REPO_LOCATION=/DATA/AppData/$AppID/data
    ports:
      - target: 1880
        published: "1880"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /data            
    x-casaos:
      ports:
        - container: "1880"
          description:
            en_us: ""
    container_name: novaas
x-casaos:
  architectures:
    - amd64
    - arm64
    - s390x
    - arm
  main: novaas
  author: CasaOS Team
  category: Developer
  description:
    en_us: Asset Administration Shell do things
  developer: Node-RED
  icon: https://raw.githubusercontent.com/mreis1986/CasaOS-AppStore/695ce2a6333dcd910cc45e889fcdb13fac1399ee/Apps/novaas/icon.png
  screenshot_link:
    - https://raw.githubusercontent.com/mreis1986/CasaOS-AppStore/695ce2a6333dcd910cc45e889fcdb13fac1399ee/Apps/novaas/icon.png
  tagline:
    en_us: Asset Administration Shell do things 2
  thumbnail: https://raw.githubusercontent.com/mreis1986/CasaOS-AppStore/695ce2a6333dcd910cc45e889fcdb13fac1399ee/Apps/novaas/icon.png
  tips: {}
  title:
    en_us: novaas
  index: /
  port_map: "1880"