version: "3.9"

services:
  novaas:
    container_name: novaas
    image: "registry.gitlab.com/novaas/catalog/nova-school-of-science-and-technology/novaas:808402e4de750530e5970b4fc247dfb968dd0075"
    restart: unless-stopped
    network_mode: "host"  # Allows access without specifying a port
    environment:
      - PORT_FORWARDING=1880  # Make sure the app runs on port 80
      - HOST=192.168.3.95
      - BROKER_SERVICE_HOST=broker.local
      - BROKER_SERVICE_PORT=1883
      - REPO_LOCATION=/data
    ports:
      - target: 1880
          published: "1880"
          protocol: tcp
    volumes:
      - /DATA/AppData/novaas/config:/config
      - /DATA/Downloads:/downloads

x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: novaas
  author: CasaOS Team
  category: Downloader 
  description:
    en_us: Asset Administration Shell do things
  developer: Uninova
  icon: https://raw.githubusercontent.com/mreis1986/CasaOS-AppStore/695ce2a6333dcd910cc45e889fcdb13fac1399ee/Apps/novaas/icon.png
  screenshot_link:
    - https://raw.githubusercontent.com/mreis1986/CasaOS-AppStore/695ce2a6333dcd910cc45e889fcdb13fac1399ee/Apps/novaas/icon.png
  tagline:
    en_us: Asset Administration Shell 
  thumbnail: https://raw.githubusercontent.com/mreis1986/CasaOS-AppStore/695ce2a6333dcd910cc45e889fcdb13fac1399ee/Apps/novaas/icon.png
  tips:
    before_install:
      en_us: |
        Default Account

        | Username | Password |
        | -------- | -------- |
        | admin   | password |
  title:
    en_us: novaas
  port_map: "1880"